from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(bill_items_model)
admin.site.register(bills_model)
admin.site.register(pay_log)
admin.site.register(income_log)
admin.site.register(purchase_model)
admin.site.register(fleet_model)
admin.site.register(machine_stock_model)
admin.site.register(vmax576_model)
admin.site.register(machine_database_model)
admin.site.register(gas_log_model)
admin.site.register(mileage_log_model)
admin.site.register(RS900_model)
admin.site.register(inventory_sheets_model)
admin.site.register(vending_finance)
admin.site.register(price_model)
admin.site.register(cantaLogs_model)
admin.site.register(FAQ_model)
admin.site.register(item_data_model)
admin.site.register(item_stock_model)
admin.site.register(machine_model_model)
admin.site.register(machine_build_model)
admin.site.register(canta_payments_model)
admin.site.register(Tenant)
admin.site.register(Property)
admin.site.register(WriteOff)
admin.site.register(Revenue)
admin.site.register(MaintenanceRequest)
admin.site.register(Transaction)
admin.site.register(UserProfile)
admin.site.register(home_inventory_model)
admin.site.register(LossStockModel)
admin.site.register(PaymentMethod)

