# Generated by Django 4.1.5 on 2023-01-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_items_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('budget_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('est_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('automotive', 'Automotive'), ('food', 'Food'), ('gas', 'Automotive'), ('phone', 'Phone'), ('rent', 'Rent'), ('studio', 'Studio'), ('music', 'Music'), ('gas', 'Alcohol'), ('extra', 'Extra'), ('personal', 'Personal')], max_length=30)),
                ('monthly_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fleet_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(max_length=6)),
                ('machine_type', models.CharField(choices=[('Snack', 'Snack Machine'), ('Brand Drink', 'Brand Drink Machine'), ('Combination', 'Combination Machine'), ('Glass Front Drink', 'Glass Front Drink Machine')], max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('key_id', models.CharField(max_length=10)),
                ('serial_num', models.CharField(max_length=15)),
                ('buy_price', models.IntegerField()),
                ('date_bought', models.DateField()),
                ('location_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('contact_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('in_service', models.DateField(blank=True, null=True)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('next_servicing', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=600)),
                ('active', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gas_log_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('actual_cost', models.FloatField()),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='income_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('first', '1st'), ('second', '2nd'), ('expense', 'Expense'), ('music', 'Music'), ('extra', 'Extra')], max_length=30)),
                ('describe', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='machine_database_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Snack', 'Snack Machine'), ('Drink', 'Drink Machine'), ('Combination', 'Combination Machine')], max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('model_num', models.CharField(max_length=30)),
                ('drink_slots', models.IntegerField()),
                ('snack_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mileage_log_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('mileage', models.FloatField()),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='pay_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('automotive', 'Automotive'), ('food', 'Food'), ('gas', 'Automotive'), ('phone', 'Phone'), ('rent', 'Rent'), ('studio', 'Studio'), ('music', 'Music'), ('gas', 'Alcohol'), ('extra', 'Extra'), ('personal', 'Personal')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='machine_stock_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('cost_per_unit', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('vendor', models.CharField(max_length=30)),
                ('qty_per_unit', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('discontinued', models.BooleanField(default=False, null=True)),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_bills.fleet_model')),
            ],
        ),
        migrations.CreateModel(
            name='AP_7640_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('technician', models.CharField(max_length=30)),
                ('condition', models.CharField(choices=[('Needs Maintenance ', 'Needs Maintenance '), ('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Satisfactory', 'Satisfactory'), ('Great', 'Great')], max_length=30)),
                ('collected', models.FloatField()),
                ('item_name_1', models.CharField(max_length=30)),
                ('stock_1', models.CharField(max_length=200)),
                ('sold_1', models.CharField(max_length=200)),
                ('added_1', models.CharField(max_length=200)),
                ('notes_1', models.CharField(max_length=600)),
                ('item_name_2', models.CharField(max_length=30)),
                ('stock_2', models.CharField(max_length=200)),
                ('sold_2', models.CharField(max_length=200)),
                ('added_2', models.CharField(max_length=200)),
                ('notes_2', models.CharField(max_length=600)),
                ('item_name_3', models.CharField(max_length=30)),
                ('stock_3', models.CharField(max_length=200)),
                ('sold_3', models.CharField(max_length=200)),
                ('added_3', models.CharField(max_length=200)),
                ('notes_3', models.CharField(max_length=600)),
                ('item_name_4', models.CharField(max_length=30)),
                ('stock_4', models.CharField(max_length=200)),
                ('sold_4', models.CharField(max_length=200)),
                ('added_4', models.CharField(max_length=200)),
                ('notes_4', models.CharField(max_length=600)),
                ('item_name_5', models.CharField(max_length=30)),
                ('stock_5', models.CharField(max_length=200)),
                ('sold_5', models.CharField(max_length=200)),
                ('added_5', models.CharField(max_length=200)),
                ('notes_5', models.CharField(max_length=600)),
                ('item_name_6', models.CharField(max_length=30)),
                ('stock_6', models.CharField(max_length=200)),
                ('sold_6', models.CharField(max_length=200)),
                ('added_6', models.CharField(max_length=200)),
                ('notes_6', models.CharField(max_length=600)),
                ('item_name_7', models.CharField(max_length=30)),
                ('stock_7', models.CharField(max_length=200)),
                ('sold_7', models.CharField(max_length=200)),
                ('added_7', models.CharField(max_length=200)),
                ('notes_7', models.CharField(max_length=600)),
                ('item_name_8', models.CharField(max_length=30)),
                ('stock_8', models.CharField(max_length=200)),
                ('sold_8', models.CharField(max_length=200)),
                ('added_8', models.CharField(max_length=200)),
                ('notes_8', models.CharField(max_length=600)),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_bills.fleet_model')),
            ],
        ),
    ]
