# Generated by Django 4.1.5 on 2023-01-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0002_bills_model_alter_bill_items_model_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills_model',
            name='charge_date_1',
        ),
        migrations.RemoveField(
            model_name='bills_model',
            name='charge_date_2',
        ),
        migrations.AddField(
            model_name='bills_model',
            name='charge_day_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bills_model',
            name='charge_day_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
