# Generated by Django 4.1.5 on 2023-02-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0004_rs900_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AP_7640_model',
            new_name='vmax576_model',
        ),
    ]
