# Generated by Django 4.1.5 on 2023-02-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0005_rename_ap_7640_model_vmax576_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_sheets_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('technician', models.CharField(max_length=30)),
                ('condition', models.CharField(choices=[('Needs Maintenance ', 'Needs Maintenance '), ('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Satisfactory', 'Satisfactory'), ('Great', 'Great')], max_length=30)),
                ('collected', models.FloatField()),
                ('data', models.CharField(max_length=300)),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_bills.fleet_model')),
            ],
        ),
    ]
