# Generated by Django 4.1.5 on 2023-02-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0006_inventory_sheets_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_sheets_model',
            name='data',
            field=models.CharField(max_length=400),
        ),
    ]
