# Generated by Django 4.1.5 on 2023-02-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0008_alter_inventory_sheets_model_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='vending_finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction', models.CharField(max_length=300)),
                ('withdrawal', models.FloatField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Automotive', 'Automotive'), ('Food', 'Food'), ('Phone', 'Phone'), ('Rent', 'Rent'), ('Studio', 'Studio'), ('Music', 'Music'), ('Alcohol', 'Alcohol'), ('Vending', 'Vending'), ('Extra', 'Extra'), ('Personal', 'Personal')], max_length=30)),
            ],
        ),
    ]
