# Generated by Django 4.1.5 on 2023-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0009_vending_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vending_finance',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Meetings', 'Meetings'), ('Gas', 'Gas'), ('Equipment', 'Equipment'), ('Restock', 'Restock'), ('Repairs', 'Repairs'), ('Alcohol', 'Alcohol'), ('Income', 'Income'), ('Other', 'Other')], max_length=30),
        ),
    ]
