# Generated by Django 4.1.5 on 2023-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0010_alter_vending_finance_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_stock_model',
            name='itemID',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vending_finance',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Meetings', 'Meetings'), ('Gas', 'Gas'), ('Equipment', 'Equipment'), ('Restock', 'Restock'), ('Repairs', 'Repairs'), ('Income', 'Income'), ('Other', 'Other')], max_length=30),
        ),
    ]
