# Generated by Django 3.2.7 on 2023-07-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0011_machine_stock_model_itemid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=20)),
                ('price_JSON', models.CharField(max_length=3000000)),
            ],
        ),
    ]
