# Generated by Django 3.2.7 on 2023-07-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0012_price_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='cantaLogs_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prev_count', models.CharField(max_length=3000000)),
                ('adding', models.CharField(max_length=3000000)),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_bills.fleet_model')),
            ],
        ),
    ]
