# Generated by Django 3.2.7 on 2023-07-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0013_cantalogs_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantalogs_model',
            name='sold',
            field=models.CharField(default='none', max_length=3000000),
            preserve_default=False,
        ),
    ]
