# Generated by Django 3.2.7 on 2023-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0014_cantalogs_model_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_1',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_2',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_3',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_4',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_5',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_6',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_7',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='added_8',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_1',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_2',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_3',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_4',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_5',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_6',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_7',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='notes_8',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_1',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_2',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_3',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_4',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_5',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_6',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_7',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='sold_8',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_1',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_2',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_3',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_4',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_5',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_6',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_7',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='stock_8',
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_7',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmax576_model',
            name='lane_8',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
