# Generated by Django 3.2.7 on 2023-12-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0015_auto_20231201_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_1',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_2',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_3',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_4',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_5',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_6',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_7',
        ),
        migrations.RemoveField(
            model_name='vmax576_model',
            name='item_name_8',
        ),
    ]
