# Generated by Django 4.2.9 on 2024-01-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0016_auto_20231201_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=75)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=700)),
                ('link', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fleet_model',
            name='id_tag',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='fleet_model',
            name='machine_type',
            field=models.CharField(choices=[('Snack', 'Snack Machine'), ('Brand Drink', 'Brand Drink Machine'), ('Combination', 'Combination Machine'), ('Glass Front Drink', 'Glass Front Drink Machine'), ('Satallite Drink', 'Satallite Drink Machine'), ('Satallite Snack', 'Satallite Snack Machine')], max_length=30),
        ),
    ]
